# Generated by Django 5.1.7 on 2025-10-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cantovallenato", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="persona",
            options={"ordering": ["apellidos"]},
        ),
    ]
