# Generated by Django 5.0 on 2025-12-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantovallenato", "0002_alter_persona_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumvallenato",
            name="anio_graba",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
