"""
Django settings for mivalle_main project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import dj_database_url
import environ
from pathlib import Path
from dotenv import load_dotenv
from decouple import config

load_dotenv()  # Carga las variables de entorno desde el archivo .env

# Rutas base
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar django-environ 
env = environ.Env() 
environ.Env.read_env(BASE_DIR / ".env") # lee el archivo .env

# Detectar entorno: 'production' o 'local'
ENVIRONMENT = env("ENVIRONMENT", default="development")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Seguridad
# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv('DJANGO_SECRET_KEY',"django-insecure-s$%fy5auc5t8&hqa+=4$*9br-0#yw_z5-e6iu$m7q$mn=a^9!5")

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = config("DJANGO_SECRET_KEY") 
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool) 
ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default='127.0.0.1,localhost').split(',')

# Hosts permitidos
#if ENVIRONMENT == 'production':
    #ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS',
    #'mivallecanta.onrender.com').split(',')
#else:
    #ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "compressor",
    "cantovallenato.apps.CantovallenatoConfig",
    "culturadelvallenato.apps.CulturadelvallenatoConfig",
    "festivalesdelvallenato.apps.FestivalesdelvallenatoConfig",
    "promotoresdelvallenato.apps.PromotoresdelvallenatoConfig",
    "territoriodelvallenato.apps.TerritoriodelvallenatoConfig",
    "crispy_forms",
    "crispy_tailwind",    
]
CRISPY_TEMPLATE_PACK = "tailwind"
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mivalle_main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mivalle_main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://postgres:19TavoCorzo50@127.0.0.1:5432/mivallecantaDB"
    )
}

#DATABASES = {
    #'default': {
        #"ENGINE": "django.db.backends.postgresql_psycopg2",
        #"NAME": "mivallecantaDB",
        #"USER": "postgres",
        #"PASSWORD" : "19TavoCorzo50",
        #"HOST" : "127.0.0.1",
        #"PORT" : "5432",
        #} 
    #}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

# Archivos estáticos
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env("STATIC_URL", default="/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 📸 Archivos multimedia
MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / 'media'

COMPRESS_ENABLED = True
COMPRESS_ROOT = BASE_DIR / 'static'

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',
                        'django.contrib.staticfiles.finders.FileSystemFinder',
                        'django.contrib.staticfiles.finders.AppDirectoriesFinder',)


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 📡 Configuración adicional para Render
# Render recomienda detectar si estamos en su plataforma
if os.environ.get("RENDER"):
    # Forzar HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
